apiVersion: apps/v1
kind: Deployment
metadata:
  name: savannah-app
  labels:
    app: savannah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: savannah
  template:
    metadata:
      labels:
        app: savannah
    spec:
      containers:
      - name: web
        image: savannah-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: savannah-config
        - secretRef:
            name: savannah-secrets
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: savannah-service
spec:
  selector:
    app: savannah
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer